[package]
name = "pallas_vrf"
version = "0.1.0"
authors = ["iquerejeta <querejeta.azurmendi@iohk.io>", "HAL Team <hal@cardanofoundation.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
# The implementation of version 3 of the VRF function (the one used in Cardano previous to Babbage) always unsets
# the sign bit in the elligator function. However, the exposure that curve25519-dalek offers, does not allow us to
# modify the elligator function. Therefore we rely on a fork that simply sets the bit. This fork should be only
# one commit ahead over the tag of version 3.2.0. And the sole change is the sign flip.
curve25519-dalek-fork = { package = "curve25519-dalek", git = "https://github.com/txpipe/curve25519-dalek", branch = "ietf03_vrf_compat_ell2" }
getrandom = { version = "0.3", features = ["std"] }
hex = "0.4"
rand_chacha = "0.2"
rand_core = "0.5"
sha2 = "0.9"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "1"

[dev-dependencies]
assert_cmd = "2.0"
criterion = "0.3.5"
hex = "0.4.2"
predicates = "3.1"
proptest = "1.6"
rand = "0.8"
tempfile = "3.19.1"

[[bench]]
name = "vrf03"
harness = false